config/routes.rb
Rails.application.routes.draw do
  resources :work_orders
  resources :locations

  root 'work_orders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :work_orders
end

app/models/technician.rb
class Technician < ApplicationRecord
  attribute :id, :integer
  attribute :name, :string

  has_many :work_orders

end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
  belongs_to :location
  belongs_to :technicians
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to location_url(@location), notice: "Location was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to location_url(@location), notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:id, :name, :city)
    end
end

class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: %i[ show edit update destroy ]

  # GET /work_orders or /work_orders.json
  def index
    @work_orders = WorkOrder.all
  end

  # GET /work_orders/1 or /work_orders/1.json
  def show
  end

  # GET /work_orders/new
  def new
    @work_order = WorkOrder.new
  end

  # GET /work_orders/1/edit
  def edit
  end

  # POST /work_orders or /work_orders.json
  def create
    @work_order = WorkOrder.new(work_order_params)

    respond_to do |format|
      if @work_order.save
        format.html { redirect_to work_order_url(@work_order), notice: "Work order was successfully created." }
        format.json { render :show, status: :created, location: @work_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_orders/1 or /work_orders/1.json
  def update
    respond_to do |format|
      if @work_order.update(work_order_params)
        format.html { redirect_to work_order_url(@work_order), notice: "Work order was successfully updated." }
        format.json { render :show, status: :ok, location: @work_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1 or /work_orders/1.json
  def destroy
    @work_order.destroy

    respond_to do |format|
      format.html { redirect_to work_orders_url, notice: "Work order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_work_order
    @work_order = WorkOrder.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def work_order_params
    params.require(:work_order).permit(:id, :technician_id, :location_id, :time, :duration, :price)
  end
end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: %i[ show edit update destroy ]

  # GET /work_orders or /work_orders.json
  def index
    @work_orders = WorkOrder.all
    @technicians = Technician.all
    @minute = 6,7,8,9,10,11,12,1,2,3,4,5
    @locations = Location.all
  end


  # GET /work_orders/1 or /work_orders/1.json
  def show
  end

  # GET /work_orders/new
  def new
    @work_order = WorkOrder.new
  end

  # GET /work_orders/1/edit
  def edit
  end

  # POST /work_orders or /work_orders.json
  def create
    @work_order = WorkOrder.new(work_order_params)

    respond_to do |format|
      if @work_order.save
        format.html { redirect_to work_order_url(@work_order), notice: "Work order was successfully created." }
        format.json { render :show, status: :created, location: @work_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_orders/1 or /work_orders/1.json
  def update
    respond_to do |format|
      if @work_order.update(work_order_params)
        format.html { redirect_to work_order_url(@work_order), notice: "Work order was successfully updated." }
        format.json { render :show, status: :ok, location: @work_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1 or /work_orders/1.json
  def destroy
    @work_order.destroy

    respond_to do |format|
      format.html { redirect_to work_orders_url, notice: "Work order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def start_time
    @work_orders.time.strftime('%H:%m')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_order
      @work_order = WorkOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_order_params
      params.require(:work_order).permit(:id, :technician_id, :location_id, :time, :duration, :price)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TerrierAssessment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.id %></td>
        <td><%= location.name %></td>
        <td><%= location.city %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @location.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/work_orders/_form.html.erb
<%= form_with(model: work_order, local: true) do |form| %>
  <% if work_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
      <% work_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :technician_id %>
    <%= form.number_field :technician_id %>
  </div>

  <div class="field">
    <%= form.label :location_id %>
    <%= form.number_field :location_id %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.datetime_select :time %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/work_orders/edit.html.erb
<h1>Editing Work Order</h1>

<%= render 'form', work_order: @work_order %>

<%= link_to 'Show', @work_order %> |
<%= link_to 'Back', work_orders_path %>

app/views/work_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Work Orders for 10/1/2019</h1>

<div class="master">


  <div>
    <div><br></div>

    <%  @minute.each do |hour| %>
      <div class="flex_time" id="hour<%= hour %>"><%= hour %></div>


    <%end %>
  </div>


  <% @technicians.each do |technician| %>
    <section class="flex-items"  style="height: 1710px; position: relative" ><%= technician.name %>
      <% @prior_work_time =  @work_orders[0].time%>
      <% @prior_work_duration = 0 %>
      <% @duration_height = 0 %>
      <% @work_order_duration_height = 0 %>
      <% @work_orders.each  do  |work_order|  %>
        <% next unless work_order.technician_id == technician.id %>
        <% first_work_time = work_order.time %>
        <% empty_id = @prior_work_time - first_work_time%>
        <% prior_height = @duration_height%>
        <div class="empty_box"
             onclick="showAlert(<%= ((((work_order.time.strftime('%H').to_i) + ((work_order.time.strftime('%M').to_i)*(1.0/100)*(7/3)))*140)-(840+prior_height))%>)" id = "<%= empty_id %>"
             style="position: absolute;
               width: 100%;
               top:<%=((((@prior_work_time.time.strftime('%H').to_i)-6)*140)+(((@prior_work_time.time.strftime('%M').to_i)/60.0)*140)+18) + ((@prior_work_duration/60.0)*140)%>px;
               height:<%= (((((work_order.time.strftime('%H').to_i)) + (((work_order.time.strftime('%M').to_i)/60.0)))*140)-(840+prior_height))%>px">


          <script> function showAlert(id){


              alert ("There is " + (id/140)*60 + " minutes between work orders" );
          }</script>

        </div>

          <div class="work_order" id="<%= work_order.id %>"
               style=" width:100%;
                 height: <%= (work_order.duration/60.0) *140 %>px;
                 position: absolute;
                 top: <%=((((work_order.time.strftime('%H').to_i)-6)*140) + (((work_order.time.strftime('%M').to_i)/60.0)*140))+18%>px">
          <% @locations.each do |location| %>
            <% next unless work_order.location_id == location.id %>
            Name:
            <%=location.name %>
            </br>
            City:
            <%= location.city %>
            </br>
            Start Time:
            <%= work_order.time.strftime('%H:%M') %>
            </br>
            Price: $
            <%= work_order.price %>

            </br>
            <% @prior_work_time = work_order.time %>
            <% @duration_height = ((work_order.duration/60.0) *140) +((((work_order.time.strftime('%H').to_i) + ((work_order.time.strftime('%M').to_i)*(1.0/100)*(7/3)))*140)-(840+prior_height) + prior_height)%>
            <% @final_box_height = @duration_height %>
              <% @prior_work_duration = work_order.duration %>
              <% @work_order_duration_height = (work_order.duration/60) *140 %>
          <%end %>







        </div>


      <% end %>
      <div class="empty_box" style="height: 1690px; border: 1px solid black"></div>

    </section>
  <%end %>


</div>
</div>

app/views/work_orders/new.html.erb
<h1>New Work Order</h1>

<%= render 'form', work_order: @work_order %>

<%= link_to 'Back', work_orders_path %>

app/views/work_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @work_order.id %>
</p>

<p>
  <strong>Technician:</strong>
  <%= @work_order.technician_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @work_order.location_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @work_order.time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @work_order.duration %>
</p>

<p>
  <strong>Price:</strong>
  <%= @work_order.price %>
</p>

<%= link_to 'Edit', edit_work_order_path(@work_order) %> |
<%= link_to 'Back', work_orders_path %>